version: '3.7'
services:
    postgres:
        image: postgres:16.0-alpine
        environment:
            - POSTGRES_HOST=${AF_POSTGRES_HOST}
            - POSTGRES_USER=${AF_POSTGRES_USER}
            - POSTGRES_PASSWORD=${AF_POSTGRES_PASSWORD}
            - POSTGRES_DB=${AF_POSTGRES_DB}
            - POSTGRES_CONTAINER_PORT=${AF_POSTGRES_CONTAINER_PORT}
        volumes:
          - ./.AirflowDB:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${AF_POSTGRES_USER}" ]
            interval: 30s
            timeout: 30s
            retries: 3
        
    db:
        image: postgres:16.0-alpine
        restart: always
        environment:
           - POSTGRES_HOST=${POSTGRES_HOST}
           - POSTGRES_USER=${POSTGRES_USER}
           - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
           - POSTGRES_DB=${POSTGRES_DB}
           - POSTGRES_CONTAINER_PORT=${POSTGRES_CONTAINER_PORT}
           - POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}
        ports: 
          - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
        volumes:
          - ./.database:/var/lib/postgresql/data
        container_name: postgres_dlhouse

    redis:
        image: 'redis:5.0.5'
        command: [
            "bash", "-c",
            '
            docker-entrypoint.sh
            --requirepass ${REDIS_PASSWORD}
            '
        ]
        restart: always

    flower:
        image: vgrover2/docker-airflow:2.7.3
        build:
          context: .
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - POSTGRES_USER=${AF_POSTGRES_USER}
            - POSTGRES_DB=${AF_POSTGRES_DB}
            - POSTGRES_HOST=${AF_POSTGRES_HOST}
            - POSTGRES_PASSWORD=${AF_POSTGRES_PASSWORD}
        ports:
            - "5555:5555"
        command: celery flower
        env_file:
            - env.list

    webserver:
        image: vgrover2/docker-airflow:2.7.3
        build:
          context: .
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - POSTGRES_USER=${AF_POSTGRES_USER}
            - POSTGRES_DB=${AF_POSTGRES_DB}
            - POSTGRES_HOST=${AF_POSTGRES_HOST}
            - POSTGRES_PASSWORD=${AF_POSTGRES_PASSWORD}
        volumes:
            - ./airflow/dags:${AIRFLOW_DAG_DIR}
            - ./airflow/logs:${AIRFLOW_LOGS_DIR}
            - ./scripts:${AIRFLOW_SCRIPTS_DIR}
            - ./plugins:${AIRFLOW_PLUGINS_DIR}
            - ./files:${AIRFLOW_FILES_DIR}
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
            - env.list

    scheduler:
        image: vgrover2/docker-airflow:2.7.3
        build:
          context: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./airflow/dags:${AIRFLOW_DAG_DIR}
            - ./scripts:${AIRFLOW_SCRIPTS_DIR}
            - ./plugins:${AIRFLOW_PLUGINS_DIR}
        environment:
            - LOAD_EX=n
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - PYTHONPATH=${PYTHONPATH}
            - POSTGRES_USER=${AF_POSTGRES_USER}
            - POSTGRES_DB=${AF_POSTGRES_DB}
            - POSTGRES_HOST=${AF_POSTGRES_HOST}
            - POSTGRES_PASSWORD=${AF_POSTGRES_PASSWORD}
        command: scheduler
        env_file:
            - env.list

    worker1:
        image: vgrover2/docker-airflow:2.7.3
        build:
          context: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./airflow/dags:${AIRFLOW_DAG_DIR}
            - ./scripts:${AIRFLOW_SCRIPTS_DIR}
            - ./plugins:${AIRFLOW_PLUGINS_DIR}
        environment:
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - PYTHONPATH=${PYTHONPATH}
            - POSTGRES_USER=${AF_POSTGRES_USER}
            - POSTGRES_DB=${AF_POSTGRES_DB}
            - POSTGRES_HOST=${AF_POSTGRES_HOST}
            - POSTGRES_PASSWORD=${AF_POSTGRES_PASSWORD}
        command: celery worker
        env_file:
            - env.list

    worker2:
        image: vgrover2/docker-airflow:2.7.3
        build:
          context: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./airflow/dags:${AIRFLOW_DAG_DIR}
            - ./scripts:${AIRFLOW_SCRIPTS_DIR}
            - ./plugins:${AIRFLOW_PLUGINS_DIR}
        environment:
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - PYTHONPATH=${PYTHONPATH}
            - POSTGRES_USER=${AF_POSTGRES_USER}
            - POSTGRES_DB=${AF_POSTGRES_DB}
            - POSTGRES_HOST=${AF_POSTGRES_HOST}
            - POSTGRES_PASSWORD=${AF_POSTGRES_PASSWORD}
        command: celery worker
        env_file:
            - env.list
