version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    db:
        image: postgres:16.0-alpine
        restart: always
        environment:
           - POSTGRES_HOST=${POSTGRES_HOST}
           - POSTGRES_USER=${POSTGRES_USER}
           - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
           - POSTGRES_DB=${POSTGRES_DB}
           - POSTGRES_CONTAINER_PORT=${POSTGRES_CONTAINER_PORT}
           - POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}
        ports: 
          - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
        volumes:
          - ./.database:/var/lib/postgresql/data
        container_name: postgres_dlhouse

    redis:
        image: redis:5.0.5

    flower:
        image: flower:latest
        build:
          context: .
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    webserver:
        image: webserver:latest
        build:
          context: .
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=/usr/local/airflow
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./scripts:/usr/local/airflow/scripts
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        image: scheduler:latest
        build:
          context: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./scripts:/usr/local/airflow/scripts
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=/usr/local/airflow
        command: scheduler

    worker1:
        image: worker1:latest
        build:
          context: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./scripts:/usr/local/airflow/scripts
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=/usr/local/airflow
        command: worker

    worker2:
        image: worker2:latest
        build:
          context: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./scripts:/usr/local/airflow/scripts
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=/usr/local/airflow
        command: worker

